# @host = https://localhost
# @port = 7018

# @Restaurant.API_HostAddress = https://localhost:7018
@token=CfDJ8CoEBB73O5hJmJvBPzbk1YruWnQBaZlNLPmPdxxrXSqUzZqUlXlbjsAs4JWoWNw1ZZErpR8fo3zr79DDZEkGe88KXb2D2AAfxOJd6vAw328UvWjVmUCmRfqw55KioPFIROPSWlGmLkGj6oyktO6z9xy0E3EMWGuvmeq9REEDh7OKkWVpFIId0g3DESjc7ta251QfKL2YIK3YevGgx-VXLRfsZ1Sz8GHDmQ0QJp3myo4978nn25516XqX14ZQ1RahIbR3i4UtDrhf-ulewM2PP0tdJHlKyTRHSqcT8osOSYyMmaUEbeFFdJ9FxaVnjgsXiF2reu4tp5fy6EYxzHltUiSdwcUvyCK_8B17eqWMzxuxfe74h_zRhFdHIK8J4XQw8Eq5qn4zU0A4sKqQHZrQHjAA-ERh2ISqVV-u2Y-9RJQ9RJGZAFz8ET4NNkTHGS_tNiGzZjy4YwuFR4kPB1Blc1lno5f3hfGDFbdMCdgYBJYidP8ws6lmENM5mf3X7522gtcfb_ytb_iCAycDRlhYl42I9qUyHIDrip75WoyO-ou1tPa68lanDX1A1_xpunMX46uc2zP76X3K_JsyQZR4JJwQVfwyT-4LVMwArNS5ulSZp3A2qIeY1JOg4RsOo8DK_kNSktfEjP1UjUP0qfMng9AiY_9f8ue5WaYWAK11Cx7Jnrn09BtV4ZuC7Q8sfuZretL90_p5VGmgjYAIdc1BDDkWaZYPVrG4Ue-hByA7gubXUhC6K-7TrPeV9NZvWPFXYP59VfCSQumEfSrlLLoUZ2-qAcZ54rYmHgqMblKmQawc


GET  https://localhost:7018/api/restaurants
Authorization: Bearer {{token}}}

###

GET https://localhost:7018/api/restaurants/1
Authorization: Bearer {{token}}}

###

DELETE https://localhost:7018/api/restaurants/12


###
PATCH https://localhost:7018/api/restaurants/11
Content-Type: application/json

{
      "Name": "Tasty Tests5",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true,
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}

###

GET https://localhost:7018/api/restaurants/1007


###


PATCH https://localhost:7018/api/restaurants/1007
Content-Type: application/json

{
  "Name": "Sample patch",
  "Description": "This is a sample restaurant description.",
  "HasDelivery": true
}

###

POST https://localhost:7018/api/restaurants/1/dishes
Content-Type: application/json

{
  "Name": "Sqpaghetti Bolognese",
  "Description": "qClassic Italian pasta dish with rich meat sauce",
  "Price": 12.9,
  "KiloCalories": 75
}

###

GET https://localhost:7018/api/restaurants/1/dishes/1

###

POST https://localhost:7018/api/identity/register
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "Password!1"
}

###

POST https://localhost:7018/api/identity/login
Content-Type: application/json

{
    "email": "owner@test.com",
    "password": "Password!1"
}
###

PATCH https://localhost:7018/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Nationality": "French",
  "DateOfBirth": "2010-01-01"
}

###


POST https://localhost:7018/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "UserEmail": "owner2@test.com",
  "RoleName": "Owner"
}

###
