# @host = https://localhost
# @port = 7018

# @Restaurant.API_HostAddress = https://localhost:7018



GET  https://localhost:7018/api/restaurants

###

GET https://localhost:7018/api/restaurants/145


###

DELETE https://localhost:7018/api/restaurants/12


###
PATCH https://localhost:7018/api/restaurants/11
Content-Type: application/json

{
      "Name": "Tasty Tests5",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true,
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}

###

GET https://localhost:7018/api/restaurants/1007


###


PATCH {{Restaurants.API_HostAddress}}/api/restaurants/1007
Content-Type: application/json

{
  "Name": "Sample patch",
  "Description": "This is a sample restaurant description.",
  "HasDelivery": true
}

###

POST https://localhost:7018/api/restaurants/6/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
}

###

GET https://localhost:7018/api/restaurants/6/dishes/3

